10 course functionality
n30w/Darkspace pull request #17
Opened 2024-03-10 03:17 UTC by reesedychiao

2024-03-10 05:44 UTC, n30w requested changes
For page.tsx files, please use "export default function [function name, like Page or Home]() {}" syntax instead of fat arrow syntax "page: any = () => {}". Fat arrow can be used for everything except page.tsx.

2024-03-10 05:44 UTC, n30w commented on frontend/src/app/components/Assignments.tsx
This is a good start, but try and break it down even more. What you can try to do is to separate the upload button/box, assignment selection box, and other components as you see fit. Remember separation of concerns. In regard to sharing state between components, like getting the value of one and putting it into the other, you can lookup NextJS or React child to parent component data passing.

2024-03-10 05:44 UTC, n30w commented on frontend/src/app/components/Courses.tsx
>  const Course: React.FC<CourseProps> = (props) => {
the React.FC<params> from TypeScript is good and appropriate here. Make sure to refactor the rest of your component code to follow this syntax and consistency. For example, the Assignments component.

2024-03-10 05:44 UTC, n30w commented on frontend/src/app/course/[id]/[id].tsx
> +"use client";
We don't need to use 'use client' here right? Leaving this as a React Server Component (RSC) is good enough, isn't it?

2024-03-10 05:44 UTC, n30w commented on frontend/src/app/components/Discussions.tsx
> +        Neo Alabastro posted on Feb 9, 2024 9:16 PM
The date part of this string can be turned into a date component.

2024-03-11 06:04 UTC, reesedychiao commented
> For page.tsx files, please use "export default function function name, like Page or Home {}" syntax instead of fat arrow syntax "page: any = () => {}". Fat arrow can be used for everything except page.tsx.

This raises an error though. I think typescript requires you to specify the type and that requires a fat arrow function?

2024-03-11 06:17 UTC, reesedychiao commented on frontend/src/app/components/Courses.tsx
>  const Course: React.FC<CourseProps> = (props) => {
I already declared the interface for other components similar to this one, is there something I need to add?

2024-03-11 14:09 UTC, n30w commented on frontend/src/app/components/Courses.tsx
>  const Course: React.FC<CourseProps> = (props) => {
No, I was just pointing out that the React.FC<> syntax is good.

2024-03-11 16:08 UTC, reesedychiao commented on frontend/src/app/components/Courses.tsx
>  const Course: React.FC<CourseProps> = (props) => {
okay nice!

2024-03-11 16:17 UTC, n30w commented
> This raises an error though. I think typescript requires you to specify the type and that requires a fat arrow function?

Strange, it doesn't raise an error for me. I'll change it to mine and we can look at it in person.

2024-03-11 16:53 UTC, n30w approved these changes
Thanks for the work @reesedychiao

2024-03-11 16:54 UTC, merged